Repository agiresearch/AIOS, pull requests merged in 2024-07, with the labels that each got.

#155 feat: add function calling support of gemini models
  README.md
  aios/llm_kernel/llm_classes/base_llm.py
  aios/llm_kernel/llm_classes/gemini_llm.py
  aios/llm_kernel/llm_classes/gpt_llm.py
  aios/llm_kernel/llm_classes/model_registry.py
  aios/llm_kernel/llm_classes/open_llm.py
  aios/llm_kernel/llm_classes/vllm.py
  requirements.txt
Labels: add documentation, add feature

#156 docs: add template for raising github issues
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/misc-discussion.yml
  .github/ISSUE_TEMPLATE/new-llm-endpoint.yml
  .github/ISSUE_TEMPLATE/usage.yml
  README.md
  aios/llm_kernel/llm_classes/gemini_llm.py
  aios/llm_kernel/llm_classes/huggingface_native_llm.py
  aios/llm_kernel/llms.py
Labels: add documentation

#159 docs: add pull request template
  .github/ISSUE_TEMPLATE/001-bug-report.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: add documentation

#160 fix: mv vllm to cuda-enable requirement file and update Dockerfile
  Dockerfile
  README.md
  aios/llm_core/README.md
  aios/llm_core/llm_classes/__init__.py
  aios/llm_core/llm_classes/base_llm.py
  aios/llm_core/llm_classes/bed_rock.py
  aios/llm_core/llm_classes/constant.py
  aios/llm_core/llm_classes/gemini_llm.py
  aios/llm_core/llm_classes/gpt_llm.py
  aios/llm_core/llm_classes/huggingface_native_llm.py
  aios/llm_core/llm_classes/model_registry.py
  aios/llm_core/llm_classes/ollama_llm.py
  aios/llm_core/llm_classes/vllm.py
  aios/llm_core/llms.py
  aios/scheduler/base.py
  eval.py
  main.py
  requirements-cuda.txt
  requirements.txt
  simulator.py
Labels: refactor, chore, fix bug

#161 feat: add agent upload/download
  README.md
  main.py
  scripts/eval/gemini.sh
  scripts/eval/gpt4.sh
  scripts/interactive/gemini.sh
  scripts/run/gemini.sh
  scripts/run/ollama_llama2.sh
  scripts/run/ollama_llama3.sh
Labels: add documentation, feature request

#162 docs: add website doc template using readthedocs
  .gitignore
  .readthedocs.yaml
  docs/Makefile
  docs/README.md
  docs/make.bat
  docs/requirements-doc.txt
  docs/source/conf.py
  docs/source/get_started/installation.rst
  docs/source/get_started/usage.rst
  docs/source/index.rst
  docs/source/openagi/installation.rst
  docs/source/openagi/usage.rst
  readthedocs.yaml
Labels: add documentation

#165 docs: add guide of installation and usage
  README.md
  docs/requirements-doc.txt
  docs/source/conf.py
  docs/source/get_started/installation.rst
  docs/source/get_started/quickstart.rst
  docs/source/get_started/usage.rst
  docs/source/index.rst
  docs/source/openagi/installation.rst
  docs/source/openagi/usage.rst
  readthedocs.yaml
  requirements.txt
Labels: add documentation

#166 fix: invalid link of quickstart
  README.md
  aios/llm_core/llm_classes/model_registry.py
  docs/source/get_started/quickstart.rst
Labels: fix bug, new llm endpoint

#167 feat: add support for claude-3-5-sonnet-20240620
  aios/llm_core/llm_classes/claude_llm.py
  aios/llm_core/llm_classes/model_registry.py
  requirements.txt
Labels: new llm endpoint

#168 chore: add pre-commit as necessity in PR template
  .github/PULL_REQUEST_TEMPLATE.md
  runtime/exec.py
  runtime/server.py
Labels: chore

#171 fix: correct the json error for gpt4
  aios/llm_core/llm_classes/model_registry.py
Labels: fix bug

#174 fix: rm unused queues
  .github/workflows/ci.yml
  pyopenagi/agents/agent_factory.py
  pyopenagi/agents/agent_process.py
  pyopenagi/agents/base_agent.py
  pyopenagi/agents/example/academic_agent/agent.py
  pyopenagi/agents/example/creation_agent/agent.py
  pyopenagi/agents/example/math_agent/agent.py
  pyopenagi/agents/example/rec_agent/agent.py
  pyopenagi/agents/example/travel_agent/agent.py
  pyopenagi/agents/react_agent.py
  requirements.txt
Labels: chore, fix bug

#175 docs: update dot-env
  .env.example
  README.md
  docs/source/conf.py
  docs/source/get_started/quickstart.rst
Labels: add documentation

#177 fix: ollama fc issues
  aios/llm_core/llm_classes/model_registry.py
  aios/llm_core/llm_classes/ollama_llm.py
  pyopenagi/agents/base_agent.py
  pyopenagi/agents/example/rec_agent/agent.py
  pyopenagi/agents/react_agent.py
  pyopenagi/tools/imdb/top_movies.py
Labels: bug

#178 perf: remove excess llm cores
  CONTRIBUTE.md
  aios/llm_core/llm_classes/model_registry.py
Labels: add documentation, optimize performance

#179 fix: json decoding error in workflow and tool call
  aios/llm_core/llm_classes/base_llm.py
  aios/llm_core/llm_classes/gemini_llm.py
  aios/llm_core/llm_classes/hf_native_llm.py
  aios/llm_core/llm_classes/ollama_llm.py
  aios/llm_core/llm_classes/vllm.py
  aios/llm_core/llms.py
  pyopenagi/agents/base_agent.py
  pyopenagi/agents/react_agent.py
  pyopenagi/utils/chat_template.py
Labels: fix bug

#184 docs: update documentation of llms and external tools
  README.md
  aios/llm_core/llm_classes/base_llm.py
  aios/llm_core/llm_classes/gpt_llm.py
  docs/source/agent_developer/agent_database.rst
  docs/source/agent_developer/agents/agent_index.rst
  docs/source/agent_developer/agents/react_agent.rst
  docs/source/conf.py
  docs/source/generate_tools.py
  docs/source/get_started/llm/claude_llm.rst
  docs/source/get_started/llm/gemini_llm.rst
  docs/source/get_started/llm/gpt_llm.rst
  docs/source/get_started/llm/hf_native_llm.rst
  docs/source/get_started/llm/llm_index.rst
  docs/source/get_started/llm/ollama.rst
  docs/source/get_started/llm/vllm.rst
  docs/source/index.rst
  pyopenagi/agents/agent_process.py
  pyopenagi/agents/interact.py
  pyopenagi/agents/react_agent.py
Labels: add documentation

#183 refactor: eval script and list_agent script
  scripts/__init__.py
  scripts/eval.py
  scripts/eval/gemini.sh
  scripts/eval/gpt4.sh
  scripts/interactive/gemini.sh
  scripts/interactive/gpt4.sh
  scripts/list_agent.py
  scripts/run/gemini.sh
  scripts/run/gpt4.sh
  scripts/run/ollama_llama2.sh
  scripts/run/ollama_llama3.sh
Labels: refactor

#186 fix: incorrect api name
  pyopenagi/tools/imdb/top_movies.py
  pyopenagi/tools/imdb/top_series.py
  tests/test_tools/test_top_series.py
Labels: fix bug

#189 fix: add tool_index.template for tool doc generation
  docs/source/agent_developer/external_tools/tool_index.rst
  docs/source/agent_developer/external_tools/tool_index.template.rst
Labels: fix bug

#195 fix: change decoding to match both list and json object
  aios/llm_core/llm_classes/base_llm.py
  aios/llm_core/llm_classes/claude_llm.py
  aios/llm_core/llm_classes/hf_native_llm.py
  aios/llm_core/llm_classes/ollama_llm.py
  aios/llm_core/llm_classes/vllm.py
Labels: fix bug

#197 refactor: revise system prompt for generating workflow in react agent
  aios/llm_core/llm_classes/gemini_llm.py
  aios/llm_core/llm_classes/vllm.py
  pyopenagi/agents/base_agent.py
  pyopenagi/agents/react_agent.py
  pyopenagi/tools/stability-ai/sdxl_turbo.py
Labels: refactor
