Repository agiresearch/AIOS, pull requests merged in 2024-08, with the labels that each got.

#199 AIOS Modularization Pt.1: Functional Components
  aios/hooks/__init__.py
  aios/hooks/llm.py
  aios/hooks/stores/__init__.py
  aios/hooks/stores/_global.py
  aios/hooks/stores/processes.py
  aios/hooks/stores/queue.py
  aios/hooks/types/__init__.py
  aios/hooks/types/hooks.py
  aios/hooks/types/llm.py
  aios/hooks/utils.py
  aios/hooks/validate.py
  aios/scheduler/fifo_scheduler.py
  main.py
  pyopenagi/agents/agent_factory.py
  pyopenagi/agents/base_agent.py
  pyopenagi/agents/example/academic_agent/agent.py
  pyopenagi/agents/interact.py
  pyopenagi/agents/react_agent.py
Labels: bug, feature request, optimize performance

#202 feat: local runtime linked to AIOS
  main.py
  requirements.txt
  runtime/server.py
  runtime/state.py
Labels: feature request

#208 feat: web ui connection with core AIOS
  .gitignore
  _exec.py
  exec.py
  main.py
  process_kill.sh
  pyopenagi/agents/interact.py
  server.py
  state.py
  web/app/agents/page.tsx
  web/app/deprecated/page.tsx
  web/app/globals.css
  web/app/page.tsx
  web/components/agents/ChatMessage.tsx
  web/python_agents/web_browsing.py
Labels: feature request

#211 feat: upgraded web ui
  README.md
  aios/hooks/llm.py
  exec.py
  web/app/page.tsx
  web/components/agents/IdeaCard.tsx
Labels: add documentation, feature request

#226 rm and relocate files in the root directory
  aios/utils/state.py
  docs/source/get_started/agent_framework/autogen.rst
  package-lock.json
  pyopenagi/agents/example/academic_agent/agent.py
  pyopenagi/agents/example/cocktail_mixlogist/agent.py
  scripts/simulator.py
  server.py
Labels: refactor
